### ISSUE TITLE
--compact contradicts --disable-keys

### ISSUE THREAD

**Issue by nchv** [wanderleihuttel/bacula-utils#4]
I am reading the section [Converting from MySQL to PostgreSQL](https://www.bacula.org/9.2.x-manuals/en/main/Installing_Configuring_Post.html#SECTION004450000000000000000) in Bacula's documentation and comparing step 2 from the process given there to `mysql_to_postresql.sh`.

According to `man mysqldump`:

```
--compact

Produce more compact output. This option enables the --skip-add-drop-table, --skip-add-locks, --skip-comments, --skip-disable-keys, and --skip-set-charset options.
```

At the same time your `mysql_to_postresql.sh` [uses `--disable-keys`](https://github.com/wanderleihuttel/bacula-utils/blob/master/convert_mysql_to_postgresql/mysql_to_postresql.sh#L40) which conflicts the `--skip-disable-keys` which `--compact` implies.

What is the reason for adding `--compact` and what is the effect of the contradiction above?

**Comment by wanderleihuttel** [comment]
Hello @anchev! I'm not an specialist in MySQL, but I've used the option --compact to not show any comments in the dump. I guess the option --skip-opt force to keep the previous options selected.

Table Version Example 1 (with --disable-keys and --compact): 
`````
mysqldump --no-create-info --no-create-db --complete-insert --compatible=postgresql --skip-quote-names --disable-keys --lock-tables --compact --skip-opt --quick -u root bacula Version > Version.sql

##############################################
INSERT INTO Version (VersionId) VALUES (16);
##############################################
`````
Table Version Example 1 (with --disable-keys and without --compact): 
`````
mysqldump --no-create-info --no-create-db --complete-insert --compatible=postgresql --skip-quote-names --disable-keys --lock-tables --skip-opt --quick -u root bacula Version > Version.sql

##############################################
-- MySQL dump 10.13  Distrib 5.7.24, for Linux (x86_64)
--
-- Host: localhost    Database: bacula
-- ------------------------------------------------------
-- Server version       5.7.24
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO,POSTGRESQL' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table "Version"
--

INSERT INTO Version (VersionId) VALUES (16);
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-11-18 19:57:34
##############################################
````

**Comment by nchv** [comment]
I am not a mysql expert either, so I checked the man page again and it says:
```
--disable-keys, -K

           For each table, surround the INSERT statements with /*!40000 ALTER TABLE
           tbl_name DISABLE KEYS */; and /*!40000 ALTER TABLE tbl_name ENABLE KEYS */;
           statements. This makes loading the dump file faster because the indexes are
           created after all rows are inserted. This option is effective only for
           nonunique indexes of MyISAM tables.
```
So it seems those comments have a performance benefit. I don't know if that would benefit the import in PostgreSQL though.

**Comment by wanderleihuttel** [comment]
I guess is because the PostgreSQL's index are different from MySQL, and the migration are made using only INSERT commands.

**Comment by nchv** [comment]
Could be. I don't know.
