### ISSUE TITLE
Tables discrepancies

### ISSUE THREAD

**Issue by nchv** [wanderleihuttel/bacula-utils#5]
Why is line 19 in `import_postgresql.sh` commented? It seems to contain the full list of table names which are available in psql after running make_bacula_tables.

**Comment by wanderleihuttel** [comment]
Hello @anchev.
Just to know all tables from Bacula catalog. 
The tables "Status" and "Version" are not necessary to import, because they are created with data inserted  in the make_bacula_tables script.

**Comment by nchv** [comment]
I see. Thanks!
