### ISSUE TITLE
Add support for baeros

### ISSUE THREAD

**Issue by tuxmaster5000** [wanderleihuttel/bacula-utils#9]
The dump of bareos 17 fails with:

> Dumping MySQL tables ...
> --------------------------------------------
> Table           Time
> --------------------------------------------
> BaseFiles       00:00:00
> mysqldump: Couldn't find table: "CDImages"
> CDImages        00:00:00
> Client          00:00:00
> mysqldump: Couldn't execute 'SELECT /*!40001 SQL_NO_CACHE */ Counter, MinValue, MaxValue, CurrentValue, WrapCounter FROM "Counters"': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'MaxValue, CurrentValue, WrapCounter FROM "Counters"' at line 1 (1064)
> Counters        00:00:00
> Device          00:00:00
> File            00:00:47
> FileSet         00:00:00
> mysqldump: Couldn't find table: "Filename"
> Filename        00:00:00
> Job             00:00:00
> JobHisto        00:00:00
> JobMedia        00:00:00
> Location        00:00:00
> LocationLog     00:00:00
> Log             00:00:00
> Media           00:00:00
> MediaType       00:00:00
> Path            00:00:01
> PathHierarchy   00:00:00
> PathVisibility  00:00:00
> Pool            00:00:00
> RestoreObject   00:00:00
> mysqldump: Couldn't find table: "Snapshot"
> Snapshot        00:00:00
> Status          00:00:00
> Storage         00:00:00
> mysqldump: Couldn't find table: "UnsavedFiles"
> UnsavedFiles    00:00:00
> Version         00:00:00
> --------------------------------------------
> Elapsed time:   00:00:48
> --------------------------------------------
> 
> 
> ERROR 1146 (42S02) at line 1: Table 'bareos.CDImages' doesn't exist
> ERROR 1146 (42S02) at line 1: Table 'bareos.Filename' doesn't exist
> ERROR 1146 (42S02) at line 1: Table 'bareos.Snapshot' doesn't exist
> ERROR 1146 (42S02) at line 1: Table 'bareos.UnsavedFiles' doesn't exist
> Total tables row count
> --------------------------------------------
> Table           Row Count
> --------------------------------------------
> basefiles              0
> client                12
> counters               0
> device                 0
> file             5270270
> fileset                4
> job                  119
> jobhisto            9635
> jobmedia            7808
> location               0
> locationlog            0
> log                 7400
> media                337
> mediatype              2
> path              190622
> pathhierarchy      51427
> pathvisibility         0
> pool                   8
> restoreobject          8
> status                21
> storage                4
> version                1
> --------------------------------------------

**Comment by tuxmaster5000** [comment]
Bareos 17 will use this tables:

> show tables;
> +--------------------+
> | Tables_in_bareos   |
> +--------------------+
> | BaseFiles          |
> | Client             |
> | Counters           |
> | Device             |
> | DeviceStats        |
> | File               |
> | FileSet            |
> | Job                |
> | JobHisto           |
> | JobMedia           |
> | JobStats           |
> | Location           |
> | LocationLog        |
> | Log                |
> | Media              |
> | MediaType          |
> | NDMPJobEnvironment |
> | NDMPLevelMap       |
> | Path               |
> | PathHierarchy      |
> | PathVisibility     |
> | Pool               |
> | Quota              |
> | RestoreObject      |
> | Status             |
> | Storage            |
> | TapeAlerts         |
> | Version            |
> +--------------------+
> 28 rows in set (0.001 sec)
>

**Comment by wanderleihuttel** [comment]
Hello @tuxmaster5000 

Just include the table names in both scripts:

````
mysql_to_postresql.sh 
line 30
tables="BaseFiles Client Counters Device DeviceStats File FileSet Job JobHisto JobMedia JobStats Location LocationLog Log Media MediaType NDMPJobEnvironment NDMPLevelMap Path PathHierarchy PathVisibility Pool Quota RestoreObject Status Storage TapeAlerts Version"


import_postgresql.sh 
line 20
tables="BaseFiles Client Counters Device DeviceStats File FileSet Job JobHisto JobMedia JobStats Location LocationLog Log Media MediaType NDMPJobEnvironment NDMPLevelMap Path PathHierarchy PathVisibility Pool Quota RestoreObject Storage TapeAlerts"
````

**Comment by tuxmaster5000** [comment]
I have added it, but one error will still occurs at the export script:
`mysqldump: Couldn't execute 'SELECT /*!40001 SQL_NO_CACHE */ Counter, MinValue, MaxValue, CurrentValue, WrapCounter FROM "Counters"': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'MaxValue, CurrentValue, WrapCounter FROM "Counters"' at line 1 (1064)`

This table exits in Bareos, but it is empty.

**Comment by wanderleihuttel** [comment]
Hello @tuxmaster5000 ! If the table is empty, try to remove from table list.
